# Generated by Django 2.2.7 on 2019-11-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_quest_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='answer',
        ),
        migrations.AddField(
            model_name='schools',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.Test'),
            preserve_default=False,
        ),
    ]
