# Generated by Django 3.0.3 on 2020-02-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20200227_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
