# Generated by Django 2.2.7 on 2019-11-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20191123_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='descritp',
            new_name='description',
        ),
    ]
