# Generated by Django 2.2.7 on 2019-11-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20191123_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='useranswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Quest')),
            ],
        ),
    ]
