# Generated by Django 2.2.7 on 2020-02-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_remove_useranswer_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='study.Quest'),
            preserve_default=False,
        ),
    ]
