# Generated by Django 2.2.7 on 2020-02-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_useranswer_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Useranswer')),
            ],
        ),
    ]
