# Generated by Django 3.0.3 on 2020-02-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20200227_1815'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
