# Generated by Django 3.0.3 on 2020-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20200227_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
