# Generated by Django 2.2.7 on 2020-02-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20200215_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='study.Userid'),
            preserve_default=False,
        ),
    ]
