# Generated by Django 2.2.7 on 2020-02-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_auto_20200215_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='test',
        ),
    ]
