# Generated by Django 2.2.7 on 2020-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_remove_userid_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='userid',
            new_name='userid1',
        ),
    ]
