# Generated by Django 2.2.7 on 2020-02-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_auto_20200215_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='userid1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.Userid'),
            preserve_default=False,
        ),
    ]
