# Generated by Django 2.2.7 on 2020-02-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_auto_20200215_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='userid1',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Userid'),
        ),
    ]
