# Generated by Django 2.2.7 on 2020-02-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_userid_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Test'),
        ),
    ]
