# Generated by Django 2.2.7 on 2020-02-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0021_userid_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='title',
        ),
    ]
