# Generated by Django 2.2.7 on 2020-02-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0022_remove_userid_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Test'),
        ),
    ]
