# Generated by Django 2.2.7 on 2020-02-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0023_userid_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userid',
            old_name='userid',
            new_name='user',
        ),
    ]
