# Generated by Django 2.2.7 on 2020-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0024_auto_20200216_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Userid',
        ),
    ]
