# Generated by Django 2.2.7 on 2020-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0025_auto_20200217_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
