# Generated by Django 2.2.7 on 2020-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0028_auto_20200218_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
