# Generated by Django 2.2.7 on 2020-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0029_auto_20200218_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
