# Generated by Django 2.2.7 on 2020-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0030_auto_20200218_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
