# Generated by Django 2.2.7 on 2020-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0032_auto_20200221_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
