# Generated by Django 2.2.7 on 2020-02-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0033_auto_20200221_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user',
            new_name='userid',
        ),
    ]
