# Generated by Django 2.2.7 on 2020-02-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0036_auto_20200221_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userid',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='userid',
            new_name='name',
        ),
    ]
