# Generated by Django 2.2.7 on 2020-02-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0037_auto_20200221_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userid',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='name',
        ),
    ]
