# Generated by Django 2.2.7 on 2020-02-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0038_auto_20200221_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Userid',
        ),
    ]
