# Generated by Django 2.2.7 on 2020-02-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0039_auto_20200221_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Userid'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
