# Generated by Django 2.2.7 on 2020-02-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0040_auto_20200221_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userid',
            new_name='User',
        ),
    ]
